SYMPTOM_KEYWORD_MAP: dict[str, str] = {
    # ── FEVER ────────────────────────────────────────────────────────────────
    "fever": "fever", "temperature": "fever", "hot body": "fever",
    "burning body": "fever", "body is hot": "fever", "tez bukhar": "high_fever",
    "high fever": "high_fever", "high temperature": "high_fever",
    "very high fever": "high_fever", "104 fever": "high_fever",
    "105 fever": "high_fever", "103 fever": "high_fever",
    "fever for 3 days": "fever_3_days", "fever since 3 days": "fever_3_days",
    "fever 3 days": "fever_3_days", "fever for 4 days": "fever_3_days",
    "fever for a week": "fever_3_days", "fever with rash": "fever_with_rash",
    "fever and rash": "fever_with_rash", "fever with chills": "fever_with_chills",
    "fever and chills": "fever_with_chills", "fever with shivering": "fever_with_chills",
    "fever with rigors": "fever_with_rigors", "fever with jaundice": "fever_with_jaundice",
    "fever with yellow eyes": "fever_with_jaundice",
    "fever with joint pain": "fever_with_joint_pain",
    "fever with bleeding gums": "fever_with_bleeding_gums",
    "chills": "chills", "shivering": "chills", "rigors": "fever_with_rigors",
    "sweating": "sweating", "night sweats": "sweating",
    "dengue": "dengue_suspected", "dengue fever": "dengue_suspected",
    "dengue suspected": "dengue_suspected", "platelet low": "dengue_suspected",
    "malaria": "malaria_suspected", "malaria fever": "malaria_suspected",
    "typhoid": "typhoid_suspected", "enteric fever": "typhoid_suspected",
    "chikungunya": "chikungunya_suspected",

    # ── CHEST / CARDIAC ───────────────────────────────────────────────────────
    "chest pain": "chest_pain", "chest tightness": "chest_pain",
    "heart pain": "chest_pain", "pain in chest": "chest_pain",
    "chest pressure": "chest_pain", "chest heaviness": "chest_pain",
    "chest discomfort": "chest_pain", "heart attack": "heart_attack",
    "cardiac arrest": "cardiac_arrest", "heart stopped": "cardiac_arrest",
    "palpitations": "palpitations_severe", "heart racing": "palpitations_severe",
    "heart pounding": "palpitations_severe", "irregular heartbeat": "palpitations_severe",
    "arm pain": "arm_pain", "left arm pain": "arm_pain",
    "jaw pain": "jaw_pain", "jaw ache": "jaw_pain",

    # ── BREATHING ─────────────────────────────────────────────────────────────
    "difficulty breathing": "difficulty_breathing",
    "breathlessness": "difficulty_breathing",
    "shortness of breath": "difficulty_breathing",
    "cant breathe": "difficulty_breathing",
    "can't breathe": "difficulty_breathing",
    "breathing problem": "difficulty_breathing",
    "breathing difficulty": "difficulty_breathing",
    "no breath": "difficulty_breathing",
    "unable to breathe": "difficulty_breathing",
    "severe breathlessness": "severe_breathlessness",
    "very hard to breathe": "severe_breathlessness",
    "gasping": "severe_breathlessness",
    "choking": "choking", "something stuck in throat": "choking",
    "food stuck": "choking", "airway blocked": "choking",
    "cyanosis": "cyanosis", "blue lips": "blue_lips",
    "lips turning blue": "blue_lips", "blue face": "cyanosis",
    "blue fingernails": "blue_fingernails", "nails turning blue": "blue_fingernails",
    "wheezing": "wheezing", "whistling breath": "wheezing",
    "asthma": "asthma_attack_moderate", "asthma attack": "asthma_attack_moderate",
    "rapid breathing": "rapid_breathing", "fast breathing": "rapid_breathing",
    "breathing fast": "rapid_breathing",
    "cough": "cough", "coughing": "cough", "dry cough": "cough",
    "wet cough": "cough", "productive cough": "cough",
    "persistent cough": "persistent_cough", "cough for weeks": "cough_3_weeks",
    "cough 3 weeks": "cough_3_weeks", "cough for 3 weeks": "cough_3_weeks",
    "coughing blood": "coughing_blood", "blood in cough": "coughing_blood",
    "blood in sputum": "coughing_blood", "hemoptysis": "coughing_blood",
    "tb": "tb_suspected", "tuberculosis": "tb_suspected",
    "tb suspected": "tb_suspected", "weight loss with cough": "tb_suspected",
    "pneumonia": "pneumonia_suspected",

    # ── NEUROLOGICAL ──────────────────────────────────────────────────────────
    "unconscious": "unconscious", "unresponsive": "unresponsive",
    "not responding": "unresponsive", "passed out": "unconscious",
    "fainted": "unconscious", "fainting": "fainting",
    "loss of consciousness": "unconscious", "blacked out": "unconscious",
    "seizure": "seizure", "fits": "seizure", "convulsion": "seizure",
    "convulsions": "seizure", "epilepsy attack": "seizure",
    "shaking uncontrollably": "seizure", "jerking": "seizure",
    "stroke": "stroke_signs", "stroke signs": "stroke_signs",
    "facial droop": "facial_droop", "face drooping": "facial_droop",
    "face drooped": "facial_droop", "one side face drooping": "facial_droop",
    "slurred speech": "slurred_speech", "speech slurred": "slurred_speech",
    "cant speak": "slurred_speech", "can't speak": "slurred_speech",
    "speech problem": "slurred_speech", "difficulty speaking": "slurred_speech",
    "arm weakness": "arm_weakness", "one arm weak": "arm_weakness",
    "sudden weakness": "sudden_weakness_one_side",
    "one side weakness": "sudden_weakness_one_side",
    "paralysis": "paralysis", "can't move": "paralysis",
    "limb not moving": "paralysis", "half body paralysis": "paralysis",
    "sudden confusion": "sudden_confusion", "confused suddenly": "sudden_confusion",
    "confusion": "confusion_mild", "disoriented": "confusion_mild",
    "not making sense": "confusion_mild",
    "sudden severe headache": "sudden_severe_headache",
    "worst headache of life": "sudden_severe_headache",
    "thunderclap headache": "sudden_severe_headache",
    "sudden headache": "sudden_headache",
    "headache": "headache", "head pain": "headache",
    "migraine": "migraine_severe", "severe migraine": "migraine_severe",
    "severe headache": "severe_headache", "bad headache": "severe_headache",
    "headache 3 days": "headache_3_days", "headache for days": "headache_3_days",
    "stiff neck": "stiff_neck", "neck stiffness": "stiff_neck",
    "neck rigid": "stiff_neck", "cannot bend neck": "stiff_neck",
    "meningitis": "meningitis_signs", "photophobia": "photophobia",
    "light sensitivity": "photophobia", "sensitive to light": "photophobia",
    "dizziness": "dizziness", "dizzy": "dizziness", "vertigo": "dizziness",
    "room spinning": "dizziness", "lightheaded": "dizziness",
    "persistent dizziness": "dizziness_persistent",
    "numbness": "numbness", "tingling": "tingling_persistent",
    "pins and needles": "tingling_persistent",
    "memory loss": "memory_loss", "forgetting things": "memory_loss",
    "vision loss": "sudden_vision_loss", "sudden vision loss": "sudden_vision_loss",
    "cannot see": "sudden_vision_loss", "blind suddenly": "sudden_vision_loss",
    "vision blurred": "vision_change", "blurred vision": "vision_change",
    "double vision": "vision_change", "vision change": "vision_change",

    # ── GASTROINTESTINAL ──────────────────────────────────────────────────────
    "stomach ache": "abdominal_pain", "stomach pain": "abdominal_pain",
    "tummy ache": "abdominal_pain", "abdominal pain": "abdominal_pain",
    "belly pain": "abdominal_pain", "pain in stomach": "abdominal_pain",
    "severe stomach pain": "severe_abdominal_pain",
    "severe abdominal pain": "severe_abdominal_pain",
    "acute abdomen": "acute_abdomen", "rigid abdomen": "rigid_abdomen",
    "hard stomach": "rigid_abdomen", "board-like abdomen": "rigid_abdomen",
    "appendicitis": "appendicitis_suspected",
    "right lower pain": "appendicitis_suspected",
    "vomiting": "vomiting", "throwing up": "vomiting",
    "vomited": "vomiting", "puking": "vomiting",
    "severe vomiting": "severe_vomiting", "vomiting repeatedly": "severe_vomiting",
    "vomiting 3 days": "vomiting_3_days", "vomiting for days": "vomiting_3_days",
    "vomiting blood": "vomiting_blood", "blood in vomit": "vomiting_blood",
    "hematemesis": "vomiting_blood", "coffee ground vomit": "vomiting_blood",
    "nausea": "nausea", "feeling sick": "nausea", "queasy": "nausea",
    "diarrhea": "diarrhea", "loose motion": "diarrhea",
    "loose stools": "diarrhea", "watery stools": "diarrhea",
    "loose potty": "diarrhea", "runny stool": "diarrhea",
    "diarrhea with blood": "diarrhea_with_blood",
    "blood in stool": "blood_in_stool", "blood in potty": "blood_in_stool",
    "bloody stool": "blood_in_stool", "rectal bleeding": "blood_in_stool",
    "black stool": "blood_in_stool", "tarry stool": "blood_in_stool",
    "diarrhea 3 days": "diarrhea_3_days", "diarrhea for days": "diarrhea_3_days",
    "dehydration": "dehydration_moderate", "very thirsty": "dehydration_moderate",
    "no urine": "dehydration_moderate", "sunken eyes": "dehydration_moderate",
    "jaundice": "jaundice", "yellow eyes": "jaundice",
    "yellow skin": "jaundice", "yellow urine": "jaundice",
    "hepatitis": "hepatitis_suspected", "liver problem": "hepatitis_suspected",
    "constipation": "constipation", "no bowel movement": "constipation",
    "cannot pass stool": "constipation",
    "food poisoning": "food_poisoning_severe",
    "ate bad food": "food_poisoning_severe",
    "gastroenteritis": "gastroenteritis_severe",

    # ── BLEEDING / TRAUMA ─────────────────────────────────────────────────────
    "bleeding": "bleeding", "blood": "bleeding",
    "heavy bleeding": "heavy_bleeding", "uncontrolled bleeding": "uncontrolled_bleeding",
    "bleeding won't stop": "uncontrolled_bleeding",
    "internal bleeding": "internal_bleeding",
    "postpartum bleeding": "postpartum_hemorrhage",
    "bleeding after delivery": "postpartum_hemorrhage",
    "snake bite": "snake_bite", "snakebite": "snake_bite",
    "bitten by snake": "snake_bite",
    "scorpion sting": "scorpion_sting", "scorpion bite": "scorpion_sting",
    "severe scorpion sting": "scorpion_sting_severe",
    "spider bite": "spider_bite",
    "dog bite": "dog_bite", "bitten by dog": "dog_bite",
    "animal bite": "animal_bite", "bitten by animal": "animal_bite",
    "rat bite": "rat_bite", "bitten by rat": "rat_bite",
    "insect bite": "insect_bite", "bee sting": "insect_bite",
    "wasp sting": "insect_bite",
    "burn": "burns_moderate", "burns": "burns_moderate",
    "severe burns": "severe_burns", "major burns": "severe_burns",
    "fire burn": "severe_burns", "chemical burn": "severe_burns",
    "electric shock": "electric_shock", "electrocution": "electric_shock",
    "head injury": "head_injury", "head trauma": "head_injury",
    "hit on head": "head_injury", "head wound": "head_injury",
    "severe head injury": "head_injury_severe",
    "spinal injury": "spinal_injury", "back injury": "spinal_injury",
    "neck injury": "spinal_injury",
    "drowning": "drowning", "near drowning": "drowning",
    "major trauma": "major_trauma", "accident": "major_trauma",
    "road accident": "major_trauma", "fall from height": "major_trauma",
    "fracture": "fracture_suspected", "broken bone": "fracture_suspected",
    "bone broken": "fracture_suspected", "suspected fracture": "fracture_suspected",
    "deep cut": "deep_cut", "deep wound": "deep_cut",
    "minor cut": "minor_cut", "small cut": "minor_cut",
    "wound": "minor_cut", "scratch": "minor_cut",
    "poisoning": "poisoning", "poison": "poisoning",
    "overdose": "overdose", "took too many pills": "overdose",
    "pesticide poisoning": "pesticide_poisoning",
    "pesticide ingestion": "pesticide_poisoning",
    "organophosphate": "organophosphate_poisoning",
    "chemical ingestion": "chemical_ingestion",
    "swallowed chemical": "chemical_ingestion",

    # ── SKIN ──────────────────────────────────────────────────────────────────
    "rash": "rash", "skin rash": "rash", "spots on skin": "rash",
    "red spots": "rash", "skin spots": "rash", "pimples": "rash",
    "blisters": "rash", "skin blisters": "rash",
    "severe rash": "severe_rash", "rash spreading": "rash_spreading",
    "rash all over body": "rash_spreading",
    "purple rash": "purple_rash", "non-blanching rash": "purple_rash",
    "petechiae": "purple_rash", "purpura": "purple_rash",
    "itching": "skin_itch", "itchy skin": "skin_itch",
    "skin itching": "skin_itch", "pruritus": "skin_itch",
    "swelling": "swelling", "edema": "swelling",
    "puffiness": "swelling", "swollen": "swelling",
    "infected wound": "infected_wound", "wound infection": "infected_wound",
    "pus in wound": "infected_wound", "wound with pus": "infected_wound",
    "abscess": "abscess", "boil": "abscess", "pus collection": "abscess",
    "cellulitis": "cellulitis", "skin infection spreading": "cellulitis",
    "red spreading skin": "cellulitis",
    "allergic reaction": "severe_allergic_reaction_mild",
    "allergy": "severe_allergic_reaction_mild",
    "anaphylaxis": "anaphylaxis", "severe allergy": "anaphylaxis",
    "throat swelling": "anaphylaxis", "face swelling after bite": "anaphylaxis",
    "hives": "rash", "urticaria": "rash",
    "chickenpox": "rash", "measles": "fever_with_rash",
    "scabies": "skin_itch",

    # ── MUSCULOSKELETAL ───────────────────────────────────────────────────────
    "body pain": "body_ache", "body ache": "body_ache",
    "muscle pain": "body_ache", "muscle ache": "body_ache",
    "myalgia": "body_ache", "generalized pain": "body_ache",
    "joint pain": "joint_pain", "joint ache": "joint_pain",
    "arthritis": "joint_pain", "knee pain": "joint_pain",
    "hip pain": "joint_pain", "shoulder pain": "joint_pain",
    "elbow pain": "joint_pain", "wrist pain": "joint_pain",
    "ankle pain": "joint_pain", "foot pain": "joint_pain",
    "severe joint pain": "severe_joint_pain",
    "joint swelling": "joint_swelling", "swollen joint": "joint_swelling",
    "back pain": "back_pain", "lower back pain": "back_pain",
    "backache": "back_pain", "spine pain": "back_pain",
    "severe back pain": "back_pain_severe",
    "neck pain": "neck_pain_severe", "neck ache": "neck_pain_severe",
    "limb pain": "limb_pain_severe", "leg pain": "limb_pain_severe",
    "arm pain severe": "limb_pain_severe",
    "weakness": "weakness", "fatigue": "weakness",
    "tiredness": "weakness", "exhaustion": "weakness",
    "very weak": "weakness", "no energy": "weakness",

    # ── EYE / EAR / NOSE / THROAT ─────────────────────────────────────────────
    "eye pain": "eye_pain_severe", "eye ache": "eye_pain_severe",
    "eye redness": "eye_infection", "red eye": "eye_infection",
    "eye discharge": "eye_infection", "eye pus": "eye_discharge_severe",
    "eye infection": "eye_infection", "conjunctivitis": "eye_infection",
    "pink eye": "eye_infection",
    "ear pain": "ear_pain", "earache": "ear_pain",
    "ear ache": "ear_pain", "pain in ear": "ear_pain",
    "severe ear pain": "ear_pain_severe",
    "ear discharge": "ear_discharge", "pus from ear": "ear_discharge",
    "ear bleeding": "ear_discharge",
    "hearing loss": "hearing_loss_sudden", "cannot hear": "hearing_loss_sudden",
    "sudden deafness": "hearing_loss_sudden",
    "runny nose": "common_cold", "blocked nose": "common_cold",
    "stuffy nose": "common_cold", "nasal congestion": "common_cold",
    "sneezing": "common_cold", "cold": "common_cold",
    "sore throat": "sore_throat", "throat pain": "sore_throat",
    "throat ache": "sore_throat", "difficulty swallowing": "sore_throat",
    "tonsils": "sore_throat", "tonsillitis": "sore_throat",
    "toothache": "severe_toothache", "tooth pain": "severe_toothache",
    "dental pain": "severe_toothache", "gum pain": "severe_toothache",
    "dental abscess": "dental_abscess", "tooth abscess": "dental_abscess",
    "swollen gum": "dental_abscess",

    # ── URINARY ───────────────────────────────────────────────────────────────
    "urinary pain": "urinary_pain", "urine pain": "urinary_pain",
    "burning urination": "urinary_pain", "burning urine": "urinary_pain",
    "pain while urinating": "urinary_pain",
    "urination pain": "urinary_pain", "dysuria": "urinary_pain",
    "severe urinary pain": "urinary_pain_severe",
    "blood in urine": "blood_in_urine", "bloody urine": "blood_in_urine",
    "hematuria": "blood_in_urine", "red urine": "blood_in_urine",
    "kidney pain": "kidney_pain", "flank pain": "kidney_pain",
    "pain in kidney area": "kidney_pain",
    "urinary retention": "urinary_retention", "cannot urinate": "urinary_retention",
    "no urine output": "urinary_retention",
    "uti": "uti_severe", "urinary infection": "uti_severe",
    "kidney stone": "kidney_stone_suspected", "renal stone": "kidney_stone_suspected",
    "stone in kidney": "kidney_stone_suspected",

    # ── OBSTETRIC / REPRODUCTIVE ──────────────────────────────────────────────
    "pregnancy": "pregnancy", "pregnant": "pregnancy",
    "pregnancy bleeding": "pregnancy_bleeding",
    "bleeding in pregnancy": "pregnancy_bleeding",
    "vaginal bleeding": "pregnancy_bleeding",
    "pregnancy pain": "pregnancy_pain",
    "pain in pregnancy": "pregnancy_pain",
    "eclampsia": "eclampsia", "fits in pregnancy": "eclampsia",
    "seizure in pregnancy": "eclampsia",
    "preeclampsia": "severe_preeclampsia",
    "high bp in pregnancy": "severe_preeclampsia",
    "swelling in pregnancy": "severe_preeclampsia",
    "placental abruption": "placental_abruption",
    "cord prolapse": "cord_prolapse",
    "obstructed labor": "obstructed_labor",
    "labor not progressing": "obstructed_labor",
    "ectopic pregnancy": "ruptured_ectopic",
    "ruptured ectopic": "ruptured_ectopic",
    "missed period": "missed_period_with_pain",
    "missed period with pain": "missed_period_with_pain",
    "vaginal discharge": "vaginal_discharge_abnormal",
    "abnormal discharge": "vaginal_discharge_abnormal",
    "foul discharge": "vaginal_discharge_abnormal",
    "pelvic pain": "pelvic_pain", "lower abdominal pain": "pelvic_pain",
    "testicular pain": "testicular_pain", "testicle pain": "testicular_pain",
    "testicular torsion": "testicular_torsion",
    "sudden testicular pain": "testicular_torsion",
    "postpartum hemorrhage": "postpartum_hemorrhage",
    "heavy bleeding after delivery": "postpartum_hemorrhage",

    # ── PEDIATRIC ─────────────────────────────────────────────────────────────
    "child not eating": "child_not_eating", "baby not feeding": "child_not_eating",
    "infant not feeding": "child_not_eating",
    "child high fever": "child_high_fever", "baby fever": "child_high_fever",
    "infant fever": "child_high_fever",
    "child rash fever": "child_rash_fever",
    "child ear pain": "child_ear_pain",
    "child diarrhea": "child_diarrhea_dehydration",
    "baby loose motion": "child_diarrhea_dehydration",
    "child vomiting": "child_vomiting_persistent",
    "baby vomiting": "child_vomiting_persistent",
    "child breathing fast": "child_breathing_fast",
    "baby breathing fast": "child_breathing_fast",
    "child pale": "child_pale", "baby pale": "child_pale",
    "child lethargic": "child_lethargic", "baby lethargic": "child_lethargic",
    "baby not responding": "infant_not_breathing",
    "newborn not breathing": "infant_not_breathing",
    "infant not breathing": "infant_not_breathing",
    "newborn seizure": "newborn_seizure", "baby fits": "newborn_seizure",
    "bulging fontanelle": "bulging_fontanelle",
    "soft spot bulging": "bulging_fontanelle",
    "not feeding infant": "not_feeding_infant",
    "severe dehydration infant": "severe_dehydration_infant",
    "meningitis infant": "meningitis_infant",

    # ── CHRONIC DISEASE ───────────────────────────────────────────────────────
    "diabetes": "diabetes", "sugar disease": "diabetes",
    "diabetic": "diabetes", "high sugar": "diabetes",
    "diabetic coma": "diabetic_coma", "sugar coma": "diabetic_coma",
    "hypoglycemia": "hypoglycemia_severe", "low sugar": "hypoglycemia_severe",
    "blood sugar low": "hypoglycemia_severe",
    "hyperglycemia": "hyperglycemia_severe", "very high sugar": "hyperglycemia_severe",
    "diabetes uncontrolled": "diabetes_uncontrolled",
    "hypertension": "hypertension", "high blood pressure": "hypertension",
    "bp high": "hypertension", "high bp": "hypertension",
    "hypertension severe": "hypertension_severe",
    "very high bp": "hypertension_severe", "bp very high": "hypertension_severe",
    "heart failure": "heart_failure_signs", "heart failure signs": "heart_failure_signs",
    "swollen legs heart": "heart_failure_signs",
    "asthma uncontrolled": "asthma_uncontrolled",
    "epilepsy": "epilepsy_uncontrolled", "epilepsy attack": "seizure",
    "low blood pressure": "low_blood_pressure",
    "bp low": "low_blood_pressure", "hypotension": "low_blood_pressure",
    "sepsis": "septic_shock", "septic shock": "septic_shock",
    "toxic shock": "toxic_shock",

    # ── HEAT / COLD ───────────────────────────────────────────────────────────
    "heat stroke": "heat_stroke", "sun stroke": "heat_stroke",
    "heat exhaustion": "heat_stroke", "overheated": "heat_stroke",
    "hypothermia": "hypothermia_severe", "very cold body": "hypothermia_severe",
    "body temperature very low": "hypothermia_severe",

    # ── MENTAL HEALTH ─────────────────────────────────────────────────────────
    "suicidal": "suicidal_thoughts", "want to die": "suicidal_thoughts",
    "suicidal thoughts": "suicidal_thoughts", "thinking of suicide": "suicidal_thoughts",
    "self harm": "self_harm", "cutting self": "self_harm",
    "hurting self": "self_harm",
    "anxiety attack": "severe_anxiety_attack",
    "panic attack": "severe_anxiety_attack",
    "psychosis": "psychosis_suspected", "hallucinations": "psychosis_suspected",
    "hearing voices": "psychosis_suspected",
    "alcohol withdrawal": "alcohol_withdrawal",
    "withdrawal symptoms": "alcohol_withdrawal",

    # ── GENERAL ───────────────────────────────────────────────────────────────
    "weight loss": "weight_loss", "losing weight": "weight_loss",
    "sudden weight loss": "weight_loss",
    "night sweats": "sweating", "sweating at night": "sweating",
    "loss of appetite": "weakness", "not eating": "weakness",
    "pale": "child_pale", "anaemia": "weakness",
    "anemia": "weakness", "low hemoglobin": "weakness",
    "general discomfort": "weakness", "not feeling well": "weakness",
    "unwell": "weakness", "sick": "fever",
    "mild cough": "cough", "mild fever": "fever",
    "mild headache": "headache", "mild pain": "body_ache",
    "stomach gas": "abdominal_pain", "acidity": "abdominal_pain",
    "heartburn": "abdominal_pain", "acid reflux": "abdominal_pain",
    "indigestion": "abdominal_pain",
}


def extract_symptoms(english_text: str) -> list[str]:
    """Extract canonical symptom codes from free text."""
    text_lower = english_text.lower()
    found = set()
    # Sort by length descending so longer/more specific phrases match first
    for phrase in sorted(SYMPTOM_KEYWORD_MAP.keys(), key=len, reverse=True):
        if phrase in text_lower:
            found.add(SYMPTOM_KEYWORD_MAP[phrase])
    return list(found)

EMERGENCY_KEYWORDS = [
    'chest pain', 'heart attack', "can't breathe", 'unconscious',
    'stroke', 'severe bleeding', 'not breathing', 'paralysis',
    'seizure', 'fits', 'poisoning', 'suicide', 'accident'
]

CLINIC_KEYWORDS = [
    'fever', 'cold', 'cough', 'vomiting', 'diarrhea', 'headache',
    'body pain', 'rash', 'infection', 'weakness', 'loose motion',
    'urine problem', 'back pain', 'ear pain', 'eye problem'
]
